language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
    - TOXENV=django-2.2
    - TOXENV=django-3.0
    - TOXENV=django-3.1
    - TOXENV=coverage
matrix:
  exclude:
    - python: 3.5
      env: TOXENV=django3.0
    - python: 3.5
      env: TOXENV=django3.1

install:
  - pip install tox

script: tox
